stages:
- test
- lint
- build

image: "node:alpine"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
    - npm ci

test:
  stage: test
  script:
    - npm run test

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
