stages:
- dependencies
- lint
- build

image: "node:13.10.1-alpine"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

dependencies:
  stage: dependencies
  sccript:
    - npm ci

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
